### ISSUE TITLE
Dependency error in Nuxt production build

### ISSUE THREAD

**Issue by stonega** [motiondivision/motion-vue#12] opened 2024-12-06 07:54 UTC
I encountered an issue when using the module in production mode. I found a solution to fix it, but I'm not sure if it's the best one. If it is, perhaps it should be mentioned in the documentation.

```typescript
// nuxt.config.ts
  vite: {
    ssr: {
      noExternal: ['motion-v'],
    },
  },
```

![Screenshot From 2024-12-06 15-46-28](https://github.com/user-attachments/assets/574e9642-07bb-4afa-ace3-0fca38d2bfc8)

**Comment by rick-hup** [comment] 2024-12-06 12:36
hey @stonega ! Can you provide a reproduction repos?

**Comment by stonega** [comment] 2024-12-06 12:58
@rick-hup 

Reproduction steps:
```
git clone https://github.com/stonega/motion-vue-demo.git
cd motion-vue-demo
yarn
yarn build
yarn preview
```

**Comment by rick-hup** [comment] 2024-12-06 14:55
@stonega  It appears to be caused by the preserveModules option generating a node_modules folder. This will be fixed in the next version.

**Closed as completed** 2024-12-07 14:31 UTC
